vcpkg_from_gitlab(
    GITLAB_URL https://git.ouryun.cn/
    OUT_SOURCE_PATH SOURCE_PATH
    REPO base/libnsq
    REF 570e8f1461b04e96e6a9dbf0161ff7e1243de827
    SHA512 0160abd35d442584826f737807d7589d291532b495790cc32b532c866114468d0a1a3d17d0887266f7cfc4ffcfd5ca7dea744297fb736b77f3bb82ddc5bb5d03
    HEAD_REF master
)

vcpkg_configure_make(
    SOURCE_PATH ${SOURCE_PATH}
    SKIP_CONFIGURE
    COPY_SOURCE
)

vcpkg_build_make(
    BUILD_TARGET all
    OPTIONS
        "CFLAGS=-I${CURRENT_INSTALLED_DIR}/include/libev"
)
vcpkg_fixup_pkgconfig()

# Install
if(NOT VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL debug)
    file(INSTALL ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg/libnsq.a DESTINATION ${CURRENT_PACKAGES_DIR}/debug/lib)
endif()
if(NOT VCPKG_BUILD_TYPE OR VCPKG_BUILD_TYPE STREQUAL release)
    file(INSTALL ${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/libnsq.a DESTINATION ${CURRENT_PACKAGES_DIR}/lib)
endif()

file(INSTALL ${SOURCE_PATH}/nsq.h DESTINATION ${CURRENT_PACKAGES_DIR}/include)
file(INSTALL ${SOURCE_PATH}/evbuffsock.h DESTINATION ${CURRENT_PACKAGES_DIR}/include)

# Handle copyright
file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)
